name: CI Monitoring Workflow
on:
  pull_request:
    types: [opened, edited]
    branches:
      - dev
    paths:
      - 'monitoring/**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    test-prometheus:
        runs-on: ubuntu-latest
        steps:
        - name: Run prometheus tests
          uses: ./.github/workflows/ci-monitoring.yaml
          with:
            monitoring-tool: 'prometheus'
    test-grafana:
        runs-on: ubuntu-latest
        steps:
        - name: Run grafana tests
          uses: ./.github/workflows/ci-monitoring.yaml
          with:
            monitoring-tool: 'grafana'
